SLOT_TYPE_POINT_GUARD = 'PG';
SLOT_TYPE_SHOOTING_GUARD = 'SG';
SLOT_TYPE_SMALL_FORWARD = 'SF';
SLOT_TYPE_POWER_FORWARD = 'PF';
SLOT_TYPE_CENTER = 'C';
SLOT_TYPE_GUARD = 'G';
SLOT_TYPE_FORWARD = 'F';
SLOT_TYPE_SHOOTING_GUARD_SMALL_FORWARD = 'SG/SF';
SLOT_TYPE_GUARD_FORWARD = 'G/F';
SLOT_TYPE_POWER_FORWARD_CENTER = 'PF/C';
SLOT_TYPE_FORWARD_CENTER = 'F/C';
SLOT_TYPE_UTIL = 'UTIL';
SLOT_TYPE_BENCH = 'Bench';
SLOT_TYPE_IR = 'IR';

POSITION_SLOT_MAPPING = {
    'PG': [SLOT_TYPE_POINT_GUARD, SLOT_TYPE_GUARD, SLOT_TYPE_GUARD_FORWARD, SLOT_TYPE_UTIL],
    'SG': [SLOT_TYPE_SHOOTING_GUARD, SLOT_TYPE_GUARD, SLOT_TYPE_SHOOTING_GUARD_SMALL_FORWARD, SLOT_TYPE_GUARD_FORWARD, SLOT_TYPE_UTIL],
    'SF': [SLOT_TYPE_SMALL_FORWARD, SLOT_TYPE_FORWARD, SLOT_TYPE_SHOOTING_GUARD_SMALL_FORWARD, SLOT_TYPE_GUARD_FORWARD, SLOT_TYPE_FORWARD_CENTER, SLOT_TYPE_UTIL],
    'PF': [SLOT_TYPE_POWER_FORWARD, SLOT_TYPE_FORWARD, SLOT_TYPE_GUARD_FORWARD, SLOT_TYPE_POWER_FORWARD_CENTER, SLOT_TYPE_FORWARD_CENTER, SLOT_TYPE_UTIL],
    'C': [SLOT_TYPE_CENTER, SLOT_TYPE_POWER_FORWARD_CENTER, SLOT_TYPE_FORWARD_CENTER, SLOT_TYPE_UTIL],
}

function parseSlotType(text) {
    switch (text) {
        case 'PG': return SLOT_TYPE_POINT_GUARD;
        case 'SG': return SLOT_TYPE_SHOOTING_GUARD;
        case 'SF': return SLOT_TYPE_SMALL_FORWARD;
        case 'PF': return SLOT_TYPE_POWER_FORWARD;
        case 'C': return SLOT_TYPE_CENTER;
        case 'G': return SLOT_TYPE_GUARD;
        case 'F': return SLOT_TYPE_FORWARD;
        case 'SG/SF': return SLOT_TYPE_SHOOTING_GUARD_SMALL_FORWARD;
        case 'G/F': return SLOT_TYPE_GUARD_FORWARD;
        case 'PF/C': return SLOT_TYPE_POWER_FORWARD_CENTER;
        case 'F/C': return SLOT_TYPE_FORWARD_CENTER;
        case 'UTIL': return SLOT_TYPE_UTIL;
        case 'Bench': return SLOT_TYPE_BENCH;
        case 'IR': return SLOT_TYPE_IR;
        default: throw new Error('Unknown slot type: ' + text);
    }
}